server:
  port: 80
#  servlet:
#    context-path: /javatest

offcn_id:
  18
offcn_name:
  xiaofei

car:
  name: 法拉利
  address: 北京
  price: 100

#spring:
#  profiles:
#    active: pro
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?serverTimezone=GMT%2B8
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.zgx.springbootdemo.pojo
